#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a firefox desktop='^2' state=floating follow=on
bspc rule -a URxvt desktop='^1'
bspc rule -a Emacs desktop='^4' state=floating follow=on

/home/mouv/.config/bspwm/autostart&
